version: '3.8'

services:
  supercollider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sc_audio
    volumes:
      - ./:/sc
      - /dev/shm:/dev/shm  # Shared memory for JACK
    ports:
      - "57120:57120/tcp"  # sclang TCP port for receiving SuperCollider code
      - "7777:7777/tcp"    # audio stream port
    environment:
      - JACK_NO_AUDIO_RESERVATION=1
    cap_add:
      - IPC_LOCK  # Allow JACK to lock memory
      - SYS_NICE  # Allow JACK to set realtime priority
    ulimits:
      memlock:
        soft: -1  # Unlimited memory locking
        hard: -1
      rtprio:
        soft: 95
        hard: 95
    shm_size: '2gb'
    stdin_open: true
    tty: true
    restart: unless-stopped
